# Nombre de la aplicaci\u00f3n
spring.application.name=Pr\u00e1ctica01 Grupo#4

# ----------------------
# PUERTO DEL SERVIDOR
# ----------------------
server.port=91

# ----------------------
# DATOS DE CONEXI\u00d3N A MYSQL
# ----------------------
spring.datasource.url=jdbc:mysql://localhost:3306/practica?useSSL=false&serverTimezone=UTC
spring.datasource.username=usuario_practica
spring.datasource.password=la_Clave
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ----------------------
# JPA / HIBERNATE
# ----------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ----------------------
# LOGGING: nivel TRACE y patr\u00f3n de consola con d\u00eda, mes, a\u00f1o, hora y minuto
# ----------------------
logging.level.root=TRACE
logging.pattern.console=%d{dd-MM-yyyy HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
